panAyer=float(input("Introduzca el número de barras de pan, con descuento, vendidas: "))
panHoy=float(input("Introduzca el número de barras de pan, de hoy, vendidas: "))
desc=float(60)
porc=(desc/100)
precio=float(3.49)
apliDesc=round((precio-(precio*porc)),2)
total=((panAyer*apliDesc)+(panHoy*precio))
print(f"El pan de hoy está a: {precio}, con descuento a: {apliDesc}")
print(f"Panes con descuento: {panAyer}, panes de hoy: {panHoy}. Coste total: {total}")
