interes=float(4)
deposit=float(input("Introduzca la cantidad de dinero inicial en su cuenta: "))
porcent=(float/100)
anio1=(deposit+((deposit*porcent)))
anio2=(anio1+((anio1*porcent)))
anio3=(anio2+((anio2*porcent)))
redondeo1=round(anio1,2)
redondeo2=round(anio2,2)
redondeo3=round(anio3,2)
print("")